Mobile Games Library
soltankara/jbe-101 pull request #141
Opened 2024-08-02 13:17 UTC by Turqut7

Project

2024-08-02 17:44 UTC, sabuhihuseynov commented on turqut/Mobile Games Library first-app/src/App.java
> +    private static int getUserOption(Scanner scanner) {
do we need this method? If user will insert wrong input we print `Invalid option. Please try again.` in switch case default. I think this method is redundant

2024-08-02 17:45 UTC, sabuhihuseynov commented on turqut/Mobile Games Library first-app/src/service/impl/MobileGamesLibraryImpl.java
> +    private Game[][] games;
why we need multidimensional array?

2024-08-02 17:46 UTC, sabuhihuseynov requested changes
pls look

2024-08-02 18:40 UTC, Turqut7 commented on turqut/Mobile Games Library first-app/src/App.java
> +    private static int getUserOption(Scanner scanner) {
if user enter non-integer input we will meet inputmissmatch exception. And this method handle exception

2024-08-02 18:45 UTC, Turqut7 commented on turqut/Mobile Games Library first-app/src/service/impl/MobileGamesLibraryImpl.java
> +    private Game[][] games;
Using a two-dimensional games array allows each game category to be stored in a separate array. This design makes it easy to manage the games of each category separately. One column for each game category and each column contains games from that category. When we use display all games option, firstofall we show category name with letter case and then games. That's why use two dimensional array.

2024-08-03 06:13 UTC, sabuhihuseynov commented on turqut/Mobile Games Library first-app/src/App.java
> +    private static int getUserOption(Scanner scanner) {
you can get input as a nextLine then

2024-08-03 06:18 UTC, merged