session13Application_Exception
soltankara/jbe-101 pull request #152
Opened 2024-08-07 20:52 UTC by Maharram-Heydarov

2024-08-07 20:59 UTC, Maharram-Heydarov commented
bu exceptionlara aid yazdığım koddu session12 də olan branchle push eledim , yeni branchle push eləyə bilmədim o commit hissəsinə gələn class yenə gəlirdi . Məndə ümümiyyətlə o classı sildim özümnən comit edib push etdim bunnan sonra düzələcək məncə

2024-08-08 07:43 UTC, sabuhihuseynov commented on maharram/src/Session13_Testing_Exception/ClassWork.java
> +            if (!("add".equalsIgnoreCase(command) || command.equalsIgnoreCase("list") || "remove".equalsIgnoreCase(command) || command.equalsIgnoreCase("quit"))) {
you can rewrite this with switch case or else if logic for more readable code

2024-08-08 07:44 UTC, sabuhihuseynov commented on maharram/src/Session13_Testing_Exception/ClassWork.java
> +            }
you already write here) Just add exception handling inside else block

2024-08-08 07:45 UTC, sabuhihuseynov requested changes
pls look

2024-08-12 19:38 UTC, sabuhihuseynov approved these changes

2024-08-12 19:38 UTC, merged