session 14
soltankara/jbe-101 pull request #156
Opened 2024-08-12 17:58 UTC by adiliso

2024-08-13 05:52 UTC, sabuhihuseynov commented on adil/src/Module02/Session14/DataAccess/ProductDao.java
> +    public List<Product> list() {
pls use verb for method naming

2024-08-13 05:54 UTC, sabuhihuseynov commented on adil/src/Module02/Session14/DataAccess/TypeDao.java
> +            Type oldType = getByName(type.getName());
Method name is save but logic inside is update

2024-08-13 05:55 UTC, sabuhihuseynov commented on adil/src/Module02/Session14/Entities/Type.java
> +    private String categoryName;
why you don't use Category object here?

2024-08-13 06:00 UTC, sabuhihuseynov commented on adil/src/Module02/Session14/Business/ProductManager.java
> +                if (!productType.isActive()) {
```
if (productType.isActive()) {
                    break;
                }
                System.out.println("Type is not active. Try again.");
```
                How about this one? I think it is more readable

2024-08-13 06:20 UTC, sabuhihuseynov requested changes
pls look

2024-08-13 07:36 UTC, adiliso commented on adil/src/Module02/Session14/Business/ProductManager.java
> +                if (!productType.isActive()) {
nice

2024-08-13 07:48 UTC, adiliso commented on adil/src/Module02/Session14/DataAccess/TypeDao.java
> +            Type oldType = getByName(type.getName());
Yes. But this method can do both operations. I don't need to write update method. I tried to compare it to Spring Boot method.

2024-08-13 08:45 UTC, adiliso commented on adil/src/Module02/Session14/Entities/Type.java
> +    private String categoryName;
onu etsem relationlari qura bilmeyecem e mence. Cetin olacaq yeni

2024-08-21 10:45 UTC, sabuhihuseynov approved these changes

2024-08-21 10:45 UTC, merged