3 easy questions
soltankara/jbe-101 pull request #164
Opened 2024-08-18 22:36 UTC by OmarTayyar

2024-08-19 07:40 UTC, sabuhihuseynov commented on omar/src/LeetCode_Easy/Remove_element_26.java
> +        Arrays.sort(nums);
I think no need to sort array

2024-08-19 07:51 UTC, sabuhihuseynov requested changes
pls look

2024-08-19 07:53 UTC, OmarTayyar commented
I will



iOS için Mail.ru uygulaması tarafından gönderildi


19 Ağustos 2024 Pazartesi 11:52 +04:00 kimden: ***@***.***  ***@***.***>:
>@sabuhihuseynov requested changes on this pull request.
>pls look
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <soltankara/jbe-101/pull/164/review/2244840179 @ github . com>

2024-08-19 08:58 UTC, sabuhihuseynov commented on omar/src/LeetCode_Easy/Remove_element_26.java
> +public class Remove_element_26 {
and pls give proper name for Classes, forExample RemoveElement, and then in comment you can write the number of the issue

2024-08-19 08:58 UTC, sabuhihuseynov requested changes
pls look

2024-08-31 14:14 UTC, sabuhihuseynov approved these changes

2024-08-31 14:14 UTC, merged