Javad homework 3
soltankara/jbe-101 pull request #41
Opened 2024-07-04 11:38 UTC by JavadNazirli

2024-07-04 12:19 UTC, sabuhihuseynov commented on javad/src/Task_day_4/hw_1.java
> +        sc = new Scanner(System.in);
you don't need create Scanner each time

2024-07-04 12:20 UTC, sabuhihuseynov requested changes
pls loook

2024-07-04 12:39 UTC, JavadNazirli commented on javad/src/Task_day_4/hw_1.java
> +        sc = new Scanner(System.in);
After the int scanner, there is a problem with the string scanner, so I did it (blockage).

2024-07-04 21:13 UTC, sabuhihuseynov commented on javad/src/Task_day_3/Book.java
> +         long priceQEPIK = 1_100L;        // Qiymet (qepikle)
adlandirmanı dəyişək pls. Böyük hərflər yanaşı gəlməməlidi

2024-07-04 21:13 UTC, sabuhihuseynov commented on javad/src/Task_day_3/Book.java
> +        System.out.println("Publishing year :"+publishingYear);
CTRL + ALT+ L

2024-07-04 21:14 UTC, sabuhihuseynov requested changes
pls look

2024-07-10 09:34 UTC, sabuhihuseynov approved these changes

2024-07-10 09:34 UTC, merged