Bahruz-hw-4
soltankara/jbe-101 pull request #47
Opened 2024-07-04 14:51 UTC by thapdigov

2024-07-04 21:19 UTC, sabuhihuseynov commented on bahruz/src/az/perfect/session3/Homework2.java
> +        String name=sc.nextLine();
CTRL + ALT + L plsss

2024-07-04 21:21 UTC, sabuhihuseynov commented on bahruz/src/az/perfect/session4/HomeWork3.java
> +        if (answer % 1 == 0) {
I didn't get id. What was that for?

2024-07-04 21:21 UTC, sabuhihuseynov requested changes
CTRL + ALT + L

2024-07-08 06:35 UTC, thapdigov commented on bahruz/src/az/perfect/session4/HomeWork3.java
> +        if (answer % 1 == 0) {
burada cavab əgər tam ədəddirsə cavabı tam versin deyə etmişəm ,məsələn cavab 5.0 kimi yox 5 kimi çıxsın deyə,əgər cavab kəsr ədəd olsa da kəsr ədəd kimi çap olunacaq

2024-07-25 20:42 UTC, closed without merging