Homework 2
soltankara/jbe-101 pull request #6
Opened 2024-07-01 20:26 UTC by alizadamuhammmed

2024-07-01 20:37 UTC, sabuhihuseynov commented on Muhammed.java
> +        int distanceKM = 232545;
Based on naming convention using two upper case letter consecutive is not desirable. instead you can use distanceKm

2024-07-01 20:38 UTC, sabuhihuseynov commented on Muhammed.java
> +        short ProductionYear2 = 2021;
Variable should start with lowerCase

2024-07-01 20:39 UTC, sabuhihuseynov commented on Muhammed.java
> +        byte Cameras = 2;
also lowerCase

2024-07-01 20:41 UTC, sabuhihuseynov requested changes
Pls look

2024-07-01 20:46 UTC, sabuhihuseynov commented on Muhammed.java
> +        long idOfStudent;
you can use only `id `

2024-07-01 20:47 UTC, sabuhihuseynov requested changes
pls look

2024-07-02 04:43 UTC, soltankara commented
@alizadamuhammmed you are supposed to clone this repo and create a branch on local. Then push your branch to this repo. Only after that a PR should be created.

2024-07-02 19:48 UTC, closed without merging