First 20 Exercises
soltankara/jbe-101 pull request #78
Opened 2024-07-08 06:48 UTC by ElshanAlasgarov

2024-07-09 05:46 UTC, sabuhihuseynov commented on elshan/src/Exercises/src/ElshanEx15.java
> +        int sum =0;
if you will use these variables only for loop, you can declare it inside loop. for instance `for (int i = 0,j =1 ;i<num; i++, j +=2  )`

2024-07-09 05:47 UTC, sabuhihuseynov commented on elshan/src/Exercises/src/ElshanEx17.java
> +        for (i = 1, j =1 ; i <= 4;i++,j = (j*10)+1){
here also declare variables inside loop

2024-07-09 05:52 UTC, sabuhihuseynov commented on elshan/src/Exercises/src/ElshanEx8.java
> +        String simvol = scanner.nextLine();
you can get char instead of String.

2024-07-09 05:52 UTC, sabuhihuseynov commented on elshan/src/Exercises/src/ElshanEx8.java
> +        if ((simvol.length() > 1) ){
and then you can remove this check

2024-07-09 05:55 UTC, sabuhihuseynov commented on elshan/src/Exercises/src/ElshanEx9.java
> +        if ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)){
you can modify this check. Because if number is not divisible by 4, it should return false without additional check.  But in this case it checks if number divisible by 400 also

2024-07-09 05:55 UTC, sabuhihuseynov requested changes
pls look

2024-07-09 07:17 UTC, ElshanAlasgarov commented on elshan/src/Exercises/src/ElshanEx9.java
> +        if ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)){
Conditions for a leap year:
Condition 1: Year is exactly divisible by 4 (year % 4 == 0).
Condition 2: However, there must be a year that is not exactly divisible by 100 (year % 100 != 0) or a year that is exactly divisible by 400 (year % 400 == 0).
Combining these two terms, we write:
if (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0) for example:
2020: 2020 % 4 = 0 and 2020 % 100 != 0
2000: 2000 % 400 = 0

2024-07-12 13:42 UTC, sabuhihuseynov commented on elshan/src/Exercises/src/ElshanEx9.java
> +        if ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)){
if year not divisible by 4 it means it is not divisible by 400 also. That impossible that number not divisible by 4 but divisible by 400. In your case if i got false from year % 4 == 0 program also checks year % 400 == 0. which is not desirable. Pls rewrite logical statement

2024-07-25 20:51 UTC, closed without merging