Homework session 4 ready
soltankara/jbe-101 pull request #84
Opened 2024-07-09 15:03 UTC by salehsamadli

2024-07-10 09:11 UTC, sabuhihuseynov commented on saleh/src/session4/Homework2.java
> +        String input = sc.nextLine();
you can directly declare char here instead of String

2024-07-10 09:12 UTC, sabuhihuseynov requested changes
pls look

2024-07-12 20:20 UTC, salehsamadli commented on saleh/src/session4/Homework2.java
> +        String input = sc.nextLine();
please review the changes

2024-07-13 07:52 UTC, sabuhihuseynov approved these changes

2024-07-13 07:52 UTC, merged