adil-lesson08
soltankara/jbe-101 pull request #90
Opened 2024-07-12 13:21 UTC by adiliso

2024-07-12 13:31 UTC, sabuhihuseynov commented on adil/src/lesson08/HomeWorks/Ex23To30.java
> +            else if (max < i) max = i;
why we need these checks?

2024-07-12 13:37 UTC, sabuhihuseynov requested changes
plss look

2024-07-12 17:39 UTC, adiliso commented on adil/src/lesson08/HomeWorks/Ex23To30.java
> +            else if (max < i) max = i;
If given array is sorted, we don't need this. Else we have to find min and max because we need to know range

2024-07-12 17:45 UTC, sabuhihuseynov commented on adil/src/lesson08/HomeWorks/Ex23To30.java
> +            else if (max < i) max = i;
Okay, good point. But I think array must be sorted because it is complicated to ask from you find missing number from unsorted array.

2024-07-13 07:54 UTC, sabuhihuseynov approved these changes

2024-07-13 07:54 UTC, merged